sphinx_themes: set version_info
Newer versions of the sphinx_rtd_theme (tested with 1.0.0) expect that
sphinx_version is set to a string containing 'x.y.z' with x=major,
y=minor, z=micro version.

Without this patch, rendering the theme explodes with:

ValueError: not enough values to unpack (expected 3, got 1)
/tmp/tmp8chn8nwv/sphinx-themes/theme/templates/layout.html:13

10{%- set sphinx_writer = 'writer-html5' if html5_doctype else 'writer-html4' -%}
11
12{# Build sphinx_version_info tuple from sphinx_version string in pure Jinja #}
13{%- set (_ver_major, _ver_minor, _ver_bugfix) = sphinx_version.split('.') | map('int') -%}
14{%- set sphinx_version_info = (_ver_major, _ver_minor, _ver_bugfix) -%}
15
16<!DOCTYPE html>

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>