jinja2: contextfunction has been replaced by pass_context
In jinja2 3.0.0, contextfunction is deprecated and has been replaced by
pass_function. Starting with 3.1.0, it is removed. So we switch to
pass_function and require jinja2 > 3.0.0 explicitly.

Without this patch, a server explodes with

flamingo server -s settings.py menu.py --port=8080 --host=localhost
ERROR:flamingo.server:setup failed
  Traceback (most recent call last):
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/utils/imports.py", line 19, in acquire
      item = importlib.import_module(item)
    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/templating/__init__.py", line 2, in <module>
      from .jinja2 import Jinja2  # NOQA
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/templating/jinja2.py", line 10, in <module>
      from jinja2 import Environment, FileSystemLoader, contextfunction
  ImportError: cannot import name 'contextfunction' from 'jinja2' ([...]/env-3.9.2/lib/python3.9/site-packages/jinja2/__init__.py)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/server/server.py", line 132, in setup
      self.build_environment.setup()
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/server/build_environment.py", line 40, in setup
      self.context.setup()
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/context.py", line 47, in setup
      templating_engine_class, path = acquire(
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/utils/imports.py", line 30, in acquire
      module = importlib.import_module(module_name)
    File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/templating/__init__.py", line 2, in <module>
      from .jinja2 import Jinja2  # NOQA
    File "[...]/env-3.9.2/lib/python3.9/site-packages/flamingo/core/templating/jinja2.py", line 10, in <module>
      from jinja2 import Environment, FileSystemLoader, contextfunction
  ImportError: cannot import name 'contextfunction' from 'jinja2' ([...]/env-3.9.2/lib/python3.9/site-packages/jinja2/__init__.py)

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>